era *.prn
era *.rel
era *.bak
rmac cxkrnl $$pz-s
rmac cxio $$pz-s
rmac cxintr $$pz-s
rmac cxramdsk $$pz-s
rmac cxkey $$pz-s
rmac cxem $$pz-s
rmac cxvt $$pz-s
rmac cx80 $$pz-s
rmac cxprinte $$pz-s
rmac cxdisk $$pz-s
rmac cxext $$pz-s
rmac cxscb $$pz-s
mac  cxkycode $$pz-s
mac  fast8502 $$pz-s
pip cx1.rel=cxkrnl.rel
pip cx2.rel=cxio.rel
pip cx3.rel=cxintr.rel
pip cx4.rel=cxramdsk.rel
pip cx5.rel=cxkey.rel
pip cx6.rel=cxem.rel
pip cx7.rel=cxvt.rel
pip cx8.rel=cx80.rel
pip cx9.rel=cxprinte.rel
pip cx10.rel=cxdisk.rel
pip cx11.rel=cxext.rel
pip cx12.rel=cxscb.rel
link bnkbios3[b]=cx1,cx2,cx3,cx5,cx6,cx7,cx8,cx9,cx10,cx4,cx11,cx12
gencpm auto
addbios fast8502
era *.sym
era cpm3.sys
